@startuml
actor ": 读者" as 读者
participant ": 预定记录" as 预定记录
participant ": 图书目录" as 图书目录
participant ": 图书信息" as 图书信息
skinparam sequenceParticipant underline
activate 读者
读者->读者:登录
读者->图书目录:查询图书目录
activate 图书目录
图书目录->图书信息:查询图书信息
activate 图书信息
图书信息-->读者:返回查询信息
deactivate 图书信息
deactivate 图书目录
读者->预定记录:查询可预定图书数量
activate 预定记录
预定记录-->读者:返回查询信息
opt 没有预定记录
读者-->图书目录:预定图书
end
opt 有预定记录
读者->图书信息:查询预定图书信息
deactivate 预定记录
end
@enduml