@startuml
usecase (预定图书)
usecase (取消预定)
usecase (读者信息管理)
usecase (查询图书)
usecase (借出图书)
usecase (归还图书)
usecase (维护书目)
usecase (查询借阅情况)
usecase (购入图书)
usecase (管理系统)

actor :图书管理员:
actor :读者:
actor :系统管理员:

:图书管理员: --> (检索图书)
:图书管理员: --> (读者信息管理)
:图书管理员: --> (维护书目)
:图书管理员: --> (查询图书)
:图书管理员: --> (查询借阅情况)

:读者: --> (查询图书)
:读者: --> (查询借阅情况)
:读者: --> (预定查询)

:系统管理员: --> (管理系统)

(维护书目) --> (购入图书) : <<include>>
(检索图书) --> (借出图书) : <<include>>
(检索图书) --> (归还图书) : <<include>>
(预定查询) --> (预定图书) : <<include>>
(预定查询) --> (取消预定) : <<include>>

@enduml