@startuml
start
:登陆图书管理系统;
:系统显示预定界面;
:参与者查询预定书籍;
if (默认查询方式？) then (yes)
  :按图书名称查询;
else (no)
  :按图书编码查询;
endif
:查询;
if (有查询结果？) then (yes)
  :参与者根据返回结果预定书籍;
else (no)
  :系统返回没有找到书籍信息;
endif
:系统存储预定信息;
stop
@enduml